# Generated by Django 3.0.2 on 2020-02-24 08:58

import adminpage.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='floor_plan')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(default=None, max_length=50, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=20)),
                ('useremail', models.CharField(default='kimtest0987678@gmail.com', max_length=256)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(default=adminpage.models.Request.two_day_hence)),
                ('progress', models.IntegerField(default=1)),
                ('floor_type', models.CharField(default='Residential', max_length=20)),
                ('commercial_type', models.CharField(default='', max_length=256)),
                ('floor_size', models.IntegerField(default=0)),
                ('floor_size_unit', models.CharField(default='m', max_length=2)),
                ('floor_height', models.CharField(blank=True, max_length=256, null=True)),
                ('floor_height_unit', models.CharField(default='m', max_length=2)),
                ('floor_address', models.TextField(blank=True, null=True)),
                ('add_request', models.TextField(blank=True, null=True)),
                ('floor_plan', models.ManyToManyField(related_name='plan_image', to='adminpage.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='sent_file')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='floor_theme')),
            ],
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='admin', max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment_file', models.ManyToManyField(blank=True, to='adminpage.SentFile')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='selected_theme',
            field=models.ManyToManyField(to='adminpage.SelectedTheme'),
        ),
        migrations.AddField(
            model_name='request',
            name='uploaded_theme',
            field=models.ManyToManyField(to='adminpage.UploadedTheme'),
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(default='requestor@gmail.com', max_length=254)),
                ('username', models.CharField(default='anonymous', max_length=20)),
                ('title', models.TextField(default='')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment_file', models.ManyToManyField(blank=True, to='adminpage.ReceivedFile')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('received_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.ReceivedMessage')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Request')),
            ],
        ),
    ]
