# Generated by Django 3.0.2 on 2020-01-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedtheme',
            old_name='option',
            new_name='photo',
        ),
    ]
