# Generated by Django 3.0.2 on 2020-02-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='sent_file'),
        ),
    ]
