# Generated by Django 3.0.2 on 2020-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_sentmessage_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='sent_file')),
            ],
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='attachment_file',
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='attachment_file',
            field=models.ManyToManyField(blank=True, to='adminpage.UploadedFile'),
        ),
    ]
