# Generated by Django 3.0.2 on 2020-02-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0017_auto_20200220_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='received_file')),
            ],
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='attachment_file',
            field=models.ManyToManyField(blank=True, to='adminpage.ReceivedFile'),
        ),
    ]
