# Generated by Django 3.0.2 on 2020-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0018_auto_20200221_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedfile',
            name='attach',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
