# Generated by Django 3.0.2 on 2020-01-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='plan_url',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='theme_url',
            new_name='photo',
        ),
    ]
