# Generated by Django 3.0.2 on 2020-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_auto_20200128_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='floor_height_unit',
            field=models.CharField(default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='floor_size_unit',
            field=models.CharField(default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='floor_type',
            field=models.CharField(default='Residential', max_length=20),
        ),
    ]
