# Generated by Django 3.0.2 on 2020-01-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20200128_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='floor_theme',
        ),
        migrations.AddField(
            model_name='request',
            name='selected_theme',
            field=models.ManyToManyField(to='adminpage.SelectedTheme'),
        ),
        migrations.AddField(
            model_name='request',
            name='uploaded_theme',
            field=models.ManyToManyField(to='adminpage.UploadedTheme'),
        ),
    ]
