# Generated by Django 3.0.2 on 2020-01-28 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_auto_20200128_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='progress',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
