# Generated by Django 3.0.2 on 2020-01-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_auto_20200128_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='floor_height',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
