# Generated by Django 3.0.2 on 2020-01-29 06:22

import adminpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_auto_20200128_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='due_at',
            field=models.DateTimeField(default=adminpage.models.Request.two_day_hence),
        ),
    ]
