# Generated by Django 3.0.2 on 2020-02-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_request_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.CharField(default='anonymous', max_length=10),
        ),
    ]
