# Generated by Django 3.0.2 on 2020-02-05 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='useremail',
            field=models.CharField(default='piaomj55@naver.com', max_length=256),
        ),
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.CharField(default='anonymous', max_length=20),
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Request')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(default='requestor@gmail.com', max_length=254)),
                ('title', models.TextField(default='')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Request')),
            ],
        ),
    ]
