# Generated by Django 3.0.2 on 2020-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_auto_20200205_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='useremail',
            field=models.CharField(default='kimtest0987678@gmail.com', max_length=256),
        ),
    ]
