# Generated by Django 3.0.2 on 2020-02-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_auto_20200205_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='username',
            field=models.CharField(default='anonymous', max_length=20),
        ),
    ]
