# Generated by Django 3.0.2 on 2020-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0011_auto_20200205_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessage',
            name='sender',
            field=models.EmailField(default='rlaxodud1122@gmail.com', max_length=254),
        ),
    ]
