# Generated by Django 3.0.2 on 2020-02-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0011_receivedmessage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='sender',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
