# Generated by Django 3.0.2 on 2020-02-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0012_auto_20200205_1827'),
        ('adminpage', '0012_sentmessage_sender'),
    ]

    operations = [
    ]
