# Generated by Django 3.0.2 on 2020-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_merge_20200206_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessage',
            name='sender',
            field=models.EmailField(default='requestor@gmail.com', max_length=254),
        ),
    ]
